# Generated by Django 4.1.1 on 2022-11-09 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.UUID('9df96194-5110-4c33-b562-dee6a2349b19'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instruments', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('musician_id', models.UUIDField(default=uuid.UUID('d0ea78b2-3ce8-4abe-86e4-fb108f108077'), editable=False, primary_key=True, serialize=False)),
                ('instruments', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('experience', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('demo', models.URLField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.UUID('12ea418d-5716-4d8d-b609-a3e6109007cb'), editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.UUID('16a45b19-0486-43b7-8d44-2f56c74fbaeb'), editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.event')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.UUID('5ac5807d-c64d-440c-8861-c68a62aa2a72'), editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('start_time', models.CharField(default='TBD', max_length=10)),
                ('end_time', models.CharField(default='TBD', max_length=10)),
                ('location', models.CharField(default='TBD', max_length=100)),
                ('pay', models.DecimalField(decimal_places=2, default='15.00', max_digits=7)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.event')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.musician')),
            ],
        ),
    ]
