# Generated by Django 4.1.1 on 2022-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('M', 'Musician'), ('G', 'Group')], default='M', max_length=1),
        ),
    ]
