# Generated by Django 4.1.1 on 2022-11-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_Account',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='musician_Account',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
