# Generated by Django 4.1.1 on 2022-11-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flier',
            field=models.ImageField(default='flyer.png', upload_to=''),
        ),
    ]
