# Generated by Django 4.1.1 on 2022-11-02 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options_musician_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('start_time', models.CharField(default='TBD', max_length=10)),
                ('end_time', models.CharField(default='TBD', max_length=10)),
                ('location', models.CharField(default='TBD', max_length=100)),
                ('pay', models.DecimalField(decimal_places=2, default='15.00', max_digits=7)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.musician')),
            ],
        ),
    ]
