# Generated by Django 4.1.1 on 2022-11-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_event_flier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flier',
            field=models.ImageField(blank=True, default='flyer.png', null=True, upload_to=''),
        ),
    ]
