# Generated by Django 4.1.1 on 2022-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_event_flier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='experience',
            field=models.CharField(choices=[('One Year', '0-1'), ('Two To Three Years', '2-3'), ('Four To Seven Years', '4-7'), ('Eight Or More Years', '8+')], default='B', max_length=19),
        ),
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('M', 'Musician'), ('G', 'Group')], default='M', max_length=10),
        ),
    ]
