# Generated by Django 4.1.1 on 2022-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_musician_demo_alter_musician_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='experience',
            field=models.CharField(choices=[('One Year', '0-1'), ('Two To Three Years', '2-3'), ('Four To Seven Years', '4-7'), ('Eight Or More Years', '8+')], default='One Year', max_length=19),
        ),
    ]
