# Generated by Django 4.1.1 on 2022-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_musician_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.CharField(max_length=200),
        ),
    ]
