# Generated by Django 4.1.1 on 2022-12-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_musician_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occuring',
            field=models.DateField(null=True),
        ),
    ]
