# Generated by Django 4.1.1 on 2022-12-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_event_occuring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='occuring',
            new_name='occurring',
        ),
    ]
